name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get today's date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=kartaltabak/lex-yacc
          DATE_TAG=${{ env.DATE }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$DATE_TAG ./docker

      - name: Push Docker image
        run: |
          IMAGE_NAME=kartaltabak/lex-yacc
          DATE_TAG=${{ env.DATE }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$DATE_TAG
